- name: remove old docker image
  docker_image:
    name: "{{ inventory_hostname }}"
    tag: "{{ build_vars.tag }}"
    state: absent
  become: "{{ docker_become_user is defined }}"
  become_user: "{{ docker_become_user|default(omit) }}"
  register: docker_build_result
  tags: [ never, rebuild ]

- name: perform docker build
  environment:
    DOCKER_BUILDKIT: "1"
  docker_image:
    name: "{{ inventory_hostname }}"
    tag: "{{ build_vars.tag }}"
    source: build
    push: no
    build:
      path: "{{ docker_build_directory.path }}"
      # enable skipping of pulling new FROM images
      # https://www.docker.com/increase-rate-limits
      # left to use the default docker_image default, which is *currently* yes, but will change in community.general 2.0
      pull: "{{ docker_build_pull | default(omit) }}"
  become: "{{ docker_become_user is defined }}"
  become_user: "{{ docker_become_user|default(omit) }}"
  register: docker_build_result

- name: check docker build created new image
  assert:
    fail_msg: new docker image not created. to force overwriting existing image specify --tags=all,rebuild
    that:
      - docker_build_result.changed
