- name: Set up AWS CLI for ECR Registry
  when: is_ecr_registry is defined
  include_role:
    name: aws_tools

- name: Log in to repositories
  docker_login:
    registry: "{{ registry }}"
    username: "{{ registry_username }}"
    password: "{{ registry_password }}"
  become: "{{ docker_become_user is defined }}"
  become_user: "{{ docker_become_user|default(omit) }}"
  loop: "{{ groups['docker_nodes'] }}"
  delegate_to: "{{ item }}"
  run_once: true
