- name: "{{ stage_item.object }} download object from s3 bucket"
  # https://docs.ansible.com/ansible/latest/collections/amazon/aws/s3_object_module.html
  amazon.aws.s3_object:
    bucket: "{{ stage_item.bucket }}"
    object: "{{ stage_item.object }}"
    dest: "{{ stage_dest }}/{{ stage_item.object | basename }}" # filename only, cannot include path, otherwise, download will fail
    access_key: "{{ s3_access_key_id }}"
    secret_key: "{{ s3_secret_access_key }}"
    mode: get
  register: downloaded_file
  # downloaded_file is as it would be _before_ changed_when is considered
  #   # so we reference it here to see what .changed would be if we didn't override it
  #     # if we are going to unarchive the file, consider the download a non-change (because we'll delete it after unarchive)
  changed_when: downloaded_file.changed and not stage_item.unarchive|default(false)

- name: "{{ stage_item.object }} unarchive downloaded object"
  when: stage_item.unarchive | default(false)
  block:
    - name: "{{ stage_dest }} unarchive"
      unarchive:
        src: "{{ stage_dest }}/{{ stage_item.object | basename }}"
        remote_src: true
        dest: "{{ stage_dest }}"
        mode: "{{ stage_item.mode | default(omit) }}"

    - name: "{{ stage_dest }} remove archive file"
      file:
        path: "{{ stage_dest }}/{{ stage_item.object | basename  }}"
        state: absent
      # removing the archive file is a non-change, because it will be re-downloaded every time
      # the unarchive step is the real indication of changed/not changed
      changed_when: false
