- name: bring up managers not currently in the swarm
  docker_swarm:
    state: join
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    remote_addrs:
      - "{{ hostvars[active_swarm_manager]['ansible_default_ipv4']['address'] }}"
    join_token: "{{ manager_join_token }}"
  when: >
    'docker_swarm_managers' in group_names and
    manager_join_token is defined and
    (swarm_local_node_state is not defined or swarm_local_node_state != 'active')
  become: true

# workers don't return swarm_facts, so this runs even for workers already in the swarm
- name: bring up workers
  docker_swarm:
    state: join
    advertise_addr: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    remote_addrs:
      - "{{ hostvars[active_swarm_manager]['ansible_default_ipv4']['address'] }}"
    join_token: "{{ worker_join_token }}"
  when: >
    'docker_swarm_workers' in group_names and
    worker_join_token is defined and
    (swarm_local_node_state is not defined or swarm_local_node_state != 'active')
  become: true
