# the volume_ variables are templated in this role's vars/main.yml

- name: create nfs volume's persistent storage path
  file:
    path: "{{ volume_create_path }}"
    state: directory
    owner: "{{ volume_owner }}"
    group: "{{ volume_group }}"
  become: true
  when: volume_type == 'nfs' and volume_create_path != ''
  tags: volumes

# each node needs to be individually configured for the volume
- name: create volume
  docker_volume:
    name: "{{ volume_name }}"
    driver: "{{ volume_driver | default(omit) }}"
    driver_options:
      type: "{{ volume_driver_option_type | default(omit) }}"
      o: "{{ volume_driver_option_o | default(omit) }}"
      device: "{{ volume_driver_option_device | default(omit) }}"
    state: present
  become: "{{ docker_become_user is defined }}"
  become_user: "{{ docker_become_user|default(omit) }}"
  loop: "{{ groups['docker_swarm_nodes'] }}"
  delegate_to: "{{ item }}"
  tags: volumes
