# the volume_ variables are templated in this role's vars/main.yml
- name: remove volume
  docker_volume:
    name: "{{ volume_name }}"
    state: absent
  become: "{{ docker_become_user is defined }}"
  become_user: "{{ docker_become_user|default(omit) }}"
  loop: "{{ groups['docker_swarm_nodes'] }}"
  delegate_to: "{{ item }}"
  tags: volumes
